version: '3.8'
services:

  database:
    image: postgres:alpine
    restart: always
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    env_file:
      - config/config.env

  cache:
    image: redis:alpine
    restart: always

  app:
    build: config
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./volumes/nextcloud/data:/var/www/html/data
      - ./volumes/nextcloud/config:/var/www/html/config
      - ./volumes/nextcloud/themes:/var/www/html/themes
      - ./volumes/nextcloud/apps:/var/www/html/custom_apps
      - ./volumes/nextcloud/web:/var/www/html
      - ./volumes/system:/var/run
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - config/config.env
    depends_on:
      - database
      - cache

  proxy:
    image: caddy:alpine
    restart: always
    volumes:
      - ./volumes/caddy/data:/datav
      - ./volumes/caddy/config:/config
      - ./config/caddyfile:/etc/caddy/Caddyfile
      - ./volumes/system:/system
      - ./volumes/nextcloud/web:/var/www/html
    ports:
      - 80:80